import { RoomObject } from '../types'

export const ROOM_OBJECTS: RoomObject[] = [
  {
    id: 'door',
    name: 'Main Door',
    description: 'A heavy reinforced door with a digital keypad.',
    position: [0, 1.5, -4.9],
    rotation: [0, 0, 0],
    isInteractable: true,
    isLocked: true,
    puzzleId: 'keypad',
    inspectText: 'The door is locked. A keypad glows beside it.',
    isDiscovered: false,
  },
  {
    id: 'door-panel',
    name: 'Door Card Reader',
    description: 'A card reader slot next to the door.',
    position: [1.2, 1.5, -4.9],
    isInteractable: true,
    isLocked: true,
    requiredItem: 'keycard',
    inspectText: 'Insert an access card to unlock the final lock.',
    isDiscovered: false,
  },
  {
    id: 'desk',
    name: 'Study Desk',
    description: 'A sleek modern desk with a drawer.',
    position: [3, 0.8, -2],
    isInteractable: true,
    isLocked: false,
    inspectText: 'A clean desk with a locked drawer underneath.',
    isDiscovered: false,
  },
  {
    id: 'desk-drawer',
    name: 'Desk Drawer',
    description: 'A locked drawer under the desk.',
    position: [3, 0.4, -2],
    isInteractable: true,
    isLocked: true,
    requiredItem: 'key',
    containsItem: 'usb',
    inspectText: 'The drawer is locked. A small keyhole is visible.',
    isDiscovered: false,
  },
  {
    id: 'laptop',
    name: 'Laptop',
    description: 'A laptop with a login screen.',
    position: [3, 1.1, -2.2],
    isInteractable: true,
    isLocked: true,
    requiredItem: 'usb',
    containsItem: 'safe_code',
    inspectText: 'The laptop shows "INSERT USB TO CONTINUE". The screen glows blue.',
    isDiscovered: false,
  },
  {
    id: 'bookshelf',
    name: 'Bookshelf',
    description: 'A tall bookshelf with colored books.',
    position: [-4, 2, 0],
    rotation: [0, Math.PI / 2, 0],
    isInteractable: true,
    isLocked: false,
    puzzleId: 'bookshelf',
    inspectText: 'Five colored books sit on the shelf. They can be rearranged.',
    isDiscovered: false,
  },
  {
    id: 'painting',
    name: 'Wall Painting',
    description: 'A dark abstract painting on the wall.',
    position: [0, 2.2, 4.8],
    rotation: [0, Math.PI, 0],
    isInteractable: true,
    isLocked: true,
    requiredItem: 'powered-flashlight',
    containsItem: 'note2',
    inspectText: 'A dark painting. Something seems hidden beneath the surface.',
    isDiscovered: false,
  },
  {
    id: 'safe',
    name: 'Wall Safe',
    description: 'A digital safe embedded in the wall.',
    position: [4.8, 1.5, 1],
    rotation: [0, -Math.PI / 2, 0],
    isInteractable: true,
    isLocked: false,
    puzzleId: 'safe',
    inspectText: 'A secure wall safe with a digital combination lock.',
    isDiscovered: false,
  },
  {
    id: 'lamp',
    name: 'Desk Lamp',
    description: 'A modern desk lamp.',
    position: [3.5, 1.3, -1.5],
    isInteractable: true,
    isLocked: false,
    containsItem: 'key',
    inspectText: 'A sleek lamp. The base feels loose...',
    isDiscovered: false,
  },
  {
    id: 'clock',
    name: 'Wall Clock',
    description: 'A clock on the wall showing 7:39.',
    position: [-4.8, 2.5, -2],
    rotation: [0, Math.PI / 2, 0],
    isInteractable: true,
    isLocked: false,
    inspectText: 'The clock reads 7:39. Four colored dots mark the 12, 3, 6, and 9 positions: Red at top, Blue at right, Green at bottom, Yellow at left.',
    isDiscovered: false,
  },
  {
    id: 'pattern-panel',
    name: 'Color Panel',
    description: 'A panel with colored buttons on the wall.',
    position: [-4.8, 1.2, 2],
    rotation: [0, Math.PI / 2, 0],
    isInteractable: true,
    isLocked: false,
    puzzleId: 'pattern',
    inspectText: 'Four colored buttons glow softly: Red, Blue, Green, Yellow.',
    isDiscovered: false,
  },
  {
    id: 'flashlight-spot',
    name: 'Compartment',
    description: 'A small hidden compartment in the floor.',
    position: [-2, 0.05, -3],
    isInteractable: true,
    isLocked: false,
    containsItem: 'flashlight',
    inspectText: 'A loose floor tile reveals a small compartment.',
    isDiscovered: false,
  },
]
